apiVersion: v1
kind: Service
metadata:
  name: system-service
  labels:
    app: system
spec:
  type: NodePort
  ports:
  - port: 9080
    nodePort: 31000
    name: http
  selector:
    app: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        image: system:2.0-SNAPSHOT
        ports:
        - containerPort: 9080
